language: node_js
node_js:
  - "0.12"
  - "4"
  - "6"
  - "stable"

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

before_script:
  # ensure we are testing against latest versions of all deps when using Yarn
  - if [ "${TRAVIS_NODE_VERSION}" != "0.12" ]; then yarn upgrade; fi
